# Generated by Django 5.2.6 on 2025-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
